version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/comfyui_collab
      - SECRET_KEY=changethissecretkey
      - COMFYUI_API_URL=http://comfyui:8188/
    depends_on:
      - db
      - comfyui

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_SOCKET_URL=http://localhost:8000
    depends_on:
      - backend

  comfyui:
    image: comfyanonymous/comfyui:latest
    ports:
      - "8188:8188"
    volumes:
      - comfyui_data:/root/.cache
      - ./comfyui_workflows:/root/comfyui/workflows
      - ./comfyui_output:/root/comfyui/output
      - ./comfyui_custom_nodes:/root/comfyui/custom_nodes
      - ./comfyui_models:/root/comfyui/models
    environment:
      - EXTRA_ARGS=--listen 0.0.0.0 --port 8188

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=comfyui_collab
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  comfyui_data:
