version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-postgres}@db:5432/comfyui_collab
      - SECRET_KEY=${SECRET_KEY:-changethissecretkey}
      - COMFYUI_API_URL=http://comfyui:8188/
    depends_on:
      - db
      - comfyui
    volumes:
      - ./static:/app/static

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  comfyui:
    image: comfyanonymous/comfyui:latest
    restart: always
    ports:
      - "8188:8188"
    volumes:
      - comfyui_data:/root/.cache
      - ./comfyui_workflows:/root/comfyui/workflows
      - ./comfyui_output:/root/comfyui/output
      - ./comfyui_custom_nodes:/root/comfyui/custom_nodes
      - ./comfyui_models:/root/comfyui/models
    environment:
      - EXTRA_ARGS=--listen 0.0.0.0 --port 8188
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=comfyui_collab
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
      - comfyui

volumes:
  postgres_data:
  comfyui_data:
